# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d64be4cca5e71b7fc2c76a2defccc29e8273f9c7576d578fab6e2bad2e722962f20977bf0291113ef96c052a638770751dee699ac8893c840819fac747e7339

test:
  secret_key_base: c1cb7861ab9a37419d1054d4fe51c503097cf1cd6bec3f6878d54ceea2635d71155f3016ab9bce786fb8665a198c9d03e867599d1d2692a57443b367a88513a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
